package com.atharvredij.technicalquiz;

import android.app.ProgressDialog;
import android.content.Intent;
import android.support.annotation.NonNull;
import android.support.v7.app.AppCompatActivity;
import android.os.Bundle;
import android.text.TextUtils;
import android.util.Log;
import android.view.View;
import android.widget.Button;
import android.widget.EditText;
import android.widget.TextView;
import android.widget.Toast;

import com.google.android.gms.tasks.OnCompleteListener;
import com.google.android.gms.tasks.OnSuccessListener;
import com.google.android.gms.tasks.Task;
import com.google.firebase.auth.AuthResult;
import com.google.firebase.auth.FirebaseAuth;
import com.google.firebase.database.DatabaseReference;
import com.google.firebase.database.FirebaseDatabase;

public class SignupActivity extends AppCompatActivity {

    // UI elements
    private EditText nameET,emailET,passwordET;
    private Button signupButton;
    private TextView loginTV;

    // Firebase objects
    FirebaseAuth mAuth;
    private FirebaseDatabase mDatabase;
    private DatabaseReference mDatabaseReference;
    private ProgressDialog mProgressDialog;

    private static final String TAG = "SignupActivity";

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_signup);

        // hiding action bar
        android.support.v7.app.ActionBar actionBar = getSupportActionBar();
        actionBar.hide();

        // setting up UI
        nameET = (EditText) findViewById(R.id.input_name);
        emailET = (EditText) findViewById(R.id.input_email);
        passwordET = (EditText) findViewById(R.id.input_password);
        signupButton = (Button) findViewById(R.id.btn_signup);
        loginTV = (TextView) findViewById(R.id.link_login);
        mProgressDialog = new ProgressDialog(this);

        // Firebase setup
        mAuth = FirebaseAuth.getInstance();
        mDatabase = FirebaseDatabase.getInstance();
        mDatabaseReference = mDatabase.getReference().child("users");

        // signing up users
        signupButton.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                createNewAccount();
            }
        });


        // taking users to login page
        loginTV.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                startActivity(new Intent(SignupActivity.this, LoginActivity.class));
                finish();
            }
        });
    }


    private void createNewAccount() {
        final String name = nameET.getText().toString().trim();
        final String email = emailET.getText().toString().trim();
        String password = passwordET.getText().toString().trim();

        if (!TextUtils.isEmpty(name) && !TextUtils.isEmpty(email)
                && !TextUtils.isEmpty(password)) {

            mProgressDialog.setMessage("Creating Account...");
            mProgressDialog.show();

            mAuth.createUserWithEmailAndPassword(email, password)
                    .addOnCompleteListener(SignupActivity.this, new OnCompleteListener<AuthResult>() {
                        @Override
                        public void onComplete(@NonNull Task<AuthResult> task) {
                            if(task.isSuccessful()) {
                                // user id generated by Firebase
                                String userid = mAuth.getCurrentUser().getUid();

                                // child node of user node
                                DatabaseReference currentUserDb = mDatabaseReference.child(userid);
                                currentUserDb.child("name").setValue(name);
                                currentUserDb.child("email").setValue(email);

                                mProgressDialog.dismiss();
                                // TODO: take users to homescreen (MainActivity)
                                Toast.makeText(SignupActivity.this, "Success Signup",
                                        Toast.LENGTH_SHORT).show();
                            } else {
                                Toast.makeText(SignupActivity.this, "Signup Failed, Try again letter",
                                        Toast.LENGTH_SHORT).show();
                                mProgressDialog.dismiss();
                                // TODO: Take to Login page
                            }
                        }
                    });
        }
    }
}
